export const REQUEST_START = 'REQUEST_START';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_BLOG_FINISHED = 'REQUEST_BLOG_FINISHED';
export const REQUEST_CATEGORY_FINISHED = 'REQUEST_CATEGORY_FINISHED';
